<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
?>
<?php

require '../../../web/fpdf181/fpdf.php';

include("../../../models/pdf-generator/pdfclass.php");
include("../../../models/excel-generator/headerExcel.php");

require_once "../../../models/pdf-generator/PHPExcel-1.8/Classes/PHPExcel.php";
require_once '../../../models/pdf-generator/PHPExcel-1.8/Classes/PHPExcel/Writer/Excel2007.php';

include '../../../models/connexion.php';
include '../../../models/ravitaillement/ravitaillement.php';
include '../../../models/attribution-biens/attributionBiens.php';
include '../../../models/unite/unite.php';
include '../../../models/biens/biens.php';
include '../../../models/fournisseur/fournisseur.php';
?>

<?php

$objPHPExcel = new PHPExcel();


$objPHPExcel->setActiveSheetIndex(0)
        ->setCellValue('B4', getHeaderExcel());

$titre_document = "Receipts_report_" . date('Y-m-d');

$objPHPExcel->getProperties()->setCreator(getHeaderExcel())
        ->setLastModifiedBy(getHeaderExcel())
        ->setTitle($titre_document)
        ->setSubject("Store_inventory")
        ->setDescription("Inventory_report generated by UIGSoft")
        ->setKeywords(getHeaderExcel())
        ->setCategory(getHeaderExcel());

$label_document = "Receipts_report";

$objPHPExcel->setActiveSheetIndex(0)
        ->setCellValue('B6', $label_document);

$n = 0;


$titre = "Receipts report ";

if ((isset($_GET['use_date1'])) && (isset($_GET['use_date2']))) {
    $titre = $titre . "Starting date : " . $_GET['use_date1'] . " " . " / Ending date : " . $_GET['use_date2'];
} else {
    $titre = $titre . " Choose interval";
}


if (isset($_GET['use_biens'])) {
    $bdbiens = new BdBiens();
    $biens = $bdbiens->getBiensById($_GET['use_biens']);
    foreach ($biens as $bien) {
        $designation_biens_choosen = $bien['bDesignation'] . " / " . $bien['gDesignation'];
    }
    if (isset($designation_biens_choosen)) {
        $titre = $titre . " Item :" . $designation_biens_choosen;
    } else {
        $titre = $titre . " | Item : - ";
    }
}

$r = 10;

$designation_fournisseur = "";
$bdfournisseur = new BdFournisseur();
$fournisseurs = $bdfournisseur->getFournisseurById($_GET['use_fournisseur']);
foreach ($fournisseurs as $fournisseur) {
    $designation_fournisseur = $fournisseur['designation'];
}

if ($designation_fournisseur == "") {
    $designation_fournisseur = "All";
}

$titre_document = $titre;

if ((isset($_GET['use_numeroOrder'])) && ($_GET['use_numeroOrder'] != "none")) {

    $r++;
    $r++;

    $objPHPExcel->setActiveSheetIndex(0)
            ->setCellValueByColumnAndRow(1, $r, "")
            ->setCellValueByColumnAndRow(2, $r, utf8_decode("Order number : " . $_GET['use_numeroOrder']))
            ->setCellValueByColumnAndRow(3, $r, "")
            ->setCellValueByColumnAndRow(4, $r, "")
            ->setCellValueByColumnAndRow(5, $r, "")
            ->setCellValueByColumnAndRow(6, $r, "")
            ->setCellValueByColumnAndRow(7, $r, "")
            ->setCellValueByColumnAndRow(8, $r, "")
            ->setCellValueByColumnAndRow(9, $r, "");
}

if ((isset($_GET['use_numeroOrder'])) && ($_GET['use_numeroOrder'] != "none")) {
    $bdattributionbiens = new BdAttributionBiens();
    $attributions = $bdattributionbiens->getAttributionBiensByNumeroOrder($_GET['use_numeroOrder']);
    foreach ($attributions as $attribution) {
        $id_fournisseur = $attribution['fId'];
    }
    $bdfournisseur = new BdFournisseur();
    $fournisseurs = $bdfournisseur->getFournisseurById($id_fournisseur);
    foreach ($fournisseurs as $fournisseur) {
        $designation_fournisseur = $fournisseur['designation'];
    }
}

$r++;
$r++;

$objPHPExcel->setActiveSheetIndex(0)
        ->setCellValueByColumnAndRow(1, $r, "")
        ->setCellValueByColumnAndRow(2, $r, utf8_decode($titre_document))
        ->setCellValueByColumnAndRow(3, $r, "")
        ->setCellValueByColumnAndRow(4, $r, "")
        ->setCellValueByColumnAndRow(5, $r, "")
        ->setCellValueByColumnAndRow(6, $r, "")
        ->setCellValueByColumnAndRow(7, $r, "")
        ->setCellValueByColumnAndRow(8, $r, "")
        ->setCellValueByColumnAndRow(9, $r, "");

$r++;
$r++;

$objPHPExcel->setActiveSheetIndex(0)
        ->setCellValueByColumnAndRow(1, $r, "")
        ->setCellValueByColumnAndRow(2, $r, decode('Supplier : ') . decode($designation_fournisseur))
        ->setCellValueByColumnAndRow(3, $r, "")
        ->setCellValueByColumnAndRow(4, $r, "")
        ->setCellValueByColumnAndRow(5, $r, "")
        ->setCellValueByColumnAndRow(6, $r, "")
        ->setCellValueByColumnAndRow(7, $r, "")
        ->setCellValueByColumnAndRow(8, $r, "")
        ->setCellValueByColumnAndRow(9, $r, "");

$r++;
$r++;

$objPHPExcel->setActiveSheetIndex(0)
        ->setCellValueByColumnAndRow(1, $r, "")
        ->setCellValueByColumnAndRow(2, $r, decode('Interval : ') . decode($_GET['use_date1'] . " to " . $_GET['use_date2']))
        ->setCellValueByColumnAndRow(3, $r, "")
        ->setCellValueByColumnAndRow(4, $r, "")
        ->setCellValueByColumnAndRow(5, $r, "")
        ->setCellValueByColumnAndRow(6, $r, "")
        ->setCellValueByColumnAndRow(7, $r, "")
        ->setCellValueByColumnAndRow(8, $r, "")
        ->setCellValueByColumnAndRow(9, $r, "");

$r++;
$r++;
$r++;


$objPHPExcel->setActiveSheetIndex(0)
        ->setCellValueByColumnAndRow(1, $r, "#")
        ->setCellValueByColumnAndRow(2, $r, "Date")
        ->setCellValueByColumnAndRow(3, $r, "Order")
        ->setCellValueByColumnAndRow(4, $r, "Quantity")
        ->setCellValueByColumnAndRow(5, $r, "Unit price")
        ->setCellValueByColumnAndRow(6, $r, "Value")
        ->setCellValueByColumnAndRow(7, $r, "Axpiration date")
        ->setCellValueByColumnAndRow(8, $r, "% TVA")
        ->setCellValueByColumnAndRow(9, $r, "Value TVA");

$n = 0;
$cumul_total_sortie = 0;
$cumul_total_reste = 0;
$cumul_total = 0;
$bdravitaillement = new BdRavitaillement();
if ((isset($_GET['use_biens'])) && ($_GET['use_biens'] != 0)) {
    if ((isset($_GET['use_date1'])) && ($_GET['use_date1'] != "")) {
        $ravitaillements = $bdravitaillement->getRavitaillementBetween2DatesByIdBiens($_GET['use_date1'], $_GET['use_date2'], $_GET['use_biens']);
    } else {
        $ravitaillements = $bdravitaillement->getRavitaillementByIdBiens($_GET['use_biens']);
    }
} else {
    if ((isset($_GET['use_date1'])) && ($_GET['use_date1'] != "")) {
        $ravitaillements = $bdravitaillement->getRavitaillementBetween2Dates($_GET['use_date1'], $_GET['use_date2']);
    } else {
        $ravitaillements = $bdravitaillement->getRavitaillementAllDesc();
    }
}

if ((isset($_GET['use_numeroOrder'])) && ($_GET['use_numeroOrder'] != "none")) {
    $ravitaillements = $bdravitaillement->getRavitaillementByNumeroOrder($_GET['use_numeroOrder']);
}

$bdfournisseur = new BdFournisseur();
if ((isset($_GET['use_fournisseur'])) && ($_GET['use_fournisseur'] != 0)) {
    $fournisseurs = $bdfournisseur->getFournisseurById($_GET['use_fournisseur']);
} else {
    $fournisseurs = $bdfournisseur->getFournisseurAllDesc();
}

if ((isset($_GET['use_numeroOrder'])) && ($_GET['use_numeroOrder'] != "none")) {
    $bdattributionbiens = new BdAttributionBiens();
    $attributions = $bdattributionbiens->getAttributionBiensByNumeroOrder($_GET['use_numeroOrder']);
    foreach ($attributions as $attribution) {
        $id_fournisseur = $attribution['fId'];
    }
    $bdfournisseur = new BdFournisseur();
    $fournisseurs = $bdfournisseur->getFournisseurById($id_fournisseur);
}

$cumul_total_all = 0;
$cumul_TVA_all = 0;
foreach ($fournisseurs as $fournisseur) {
    $cumul_total_fournisseur = 0;
    $cumul_TVA_fournisseur = 0;


    $r++;
    $r++;

    $objPHPExcel->setActiveSheetIndex(0)
            ->setCellValueByColumnAndRow(1, $r, "")
            ->setCellValueByColumnAndRow(2, $r, $fournisseur['designation'])
            ->setCellValueByColumnAndRow(3, $r, "")
            ->setCellValueByColumnAndRow(4, $r, "")
            ->setCellValueByColumnAndRow(5, $r, "")
            ->setCellValueByColumnAndRow(6, $r, "")
            ->setCellValueByColumnAndRow(7, $r, "")
            ->setCellValueByColumnAndRow(8, $r, "")
            ->setCellValueByColumnAndRow(9, $r, "");


    foreach ($ravitaillements as $ravitaillement) {
        if ($ravitaillement['fournisseur_id'] == $fournisseur['id']) {
            $n++;
            $chaine_part_ravitaillement_sortie = "";
            $chaine_part_ravitaillement_reste = "";
            $v1 = $ravitaillement['id'];
            $v2 = $ravitaillement['date'];

            $bdattributionbiens = new BdAttributionBiens();
            $attributions = $bdattributionbiens->getAttributionBiensById($ravitaillement['attribution_id']);
            foreach ($attributions as $attribution) {
                $v3 = "O.id:" . $attribution['aId'] . " / " . $attribution['date'] . " / " . $attribution['bDesignation'] . " / Order qty : " . $attribution['quantite_minimale'];
            }

            $v4 = $ravitaillement['quantite'];

            $bdunite = new BdUnite();
            $unites = $bdunite->getUniteByName("-" . $ravitaillement['id'] . "-");
            foreach ($unites as $unite) {
                if (($unite['active'] == 0) && ($unite['active_principal'] == 1)) {
                    $part_code = explode('-', $unite['code']);
                    if ((strlen($part_code[1])) == 1) {
                        $chaine_part_ravitaillement_sortie = $chaine_part_ravitaillement_sortie . $part_code[1] . "-";
                    }
                }
            }
            foreach ($unites as $unite) {
                if (($unite['active'] == 1) && ($unite['active_principal'] == 1)) {
                    $part_code = explode('-', $unite['code']);
                    if ((strlen($part_code[1])) == 1) {
                        $chaine_part_ravitaillement_reste = $chaine_part_ravitaillement_reste . $part_code[1] . "-";
                    }
                }
            }

            $items_ravitaillement = explode('-', $chaine_part_ravitaillement_sortie);
            $n_same_ravitaillement = 0;
            $cumule_prix = 0;
            foreach ($items_ravitaillement as $item) {
                if ((strlen($item)) == 1) {
                    $bdravitaillement_second = new BdRavitaillement();
                    $ravitaillements_second = $bdravitaillement_second->getRavitaillementById($item);
                    $last = 0;
                    $i = 0;
                    $j = 0;
                    $prix_item = 0;
                    foreach ($ravitaillements_second as $ravitaillement_second) {
                        $i++;
                    }
                    foreach ($ravitaillements_second as $ravitaillement_second) {
                        $cumule_prix = $cumule_prix + $ravitaillement_second['prix'];
                        $j++;
                    }
                }
            }
            $v5 = $cumule_prix . " USD";
            $cumul_total_sortie = $cumul_total_sortie + $cumule_prix;

            $items_ravitaillement = explode('-', $chaine_part_ravitaillement_reste);
            $n_same_ravitaillement = 0;
            $cumule_prix = 0;
            foreach ($items_ravitaillement as $item) {
                if ((strlen($item)) == 1) {
                    $bdravitaillement_second = new BdRavitaillement();
                    $ravitaillements_second = $bdravitaillement_second->getRavitaillementById($item);
                    $last = 0;
                    $i = 0;
                    $j = 0;
                    $prix_item = 0;
                    foreach ($ravitaillements_second as $ravitaillement_second) {
                        $i++;
                    }
                    foreach ($ravitaillements_second as $ravitaillement_second) {
                        $cumule_prix = $cumule_prix + $ravitaillement_second['prix'];
                        $j++;
                    }
                }
            }
            $v6 = $cumule_prix . " USD";
            $cumul_total_reste = $cumul_total_reste + $cumule_prix;

            $v7 = $ravitaillement['prix'] . " USD";
            $v8 = ($ravitaillement['quantite'] * $ravitaillement['prix']) . " USD";
            $v9 = $ravitaillement['delai_realise'];
            $v10 = $ravitaillement['dateExpiration'];
            $v11 = $ravitaillement['type'];
            $v12 = $ravitaillement['pourcentageTVA'];
            $v13 = (($ravitaillement['pourcentageTVA'] / 100) * ($ravitaillement['quantite'] * $ravitaillement['prix'])) . " USD";

            $cumul_total = $cumul_total + ($ravitaillement['quantite'] * $ravitaillement['prix']);


            $r++;

            $objPHPExcel->setActiveSheetIndex(0)
                    ->setCellValueByColumnAndRow(1, $r, $v1)
                    ->setCellValueByColumnAndRow(2, $r, $v2)
                    ->setCellValueByColumnAndRow(3, $r, $v3)
                    ->setCellValueByColumnAndRow(4, $r, $v4)
                    ->setCellValueByColumnAndRow(5, $r, $v7)
                    ->setCellValueByColumnAndRow(6, $r, $v8)
                    ->setCellValueByColumnAndRow(7, $r, $v10)
                    ->setCellValueByColumnAndRow(8, $r, $v12)
                    ->setCellValueByColumnAndRow(9, $r, $v13);



            $cumul_total_fournisseur = $cumul_total_fournisseur + ($ravitaillement['quantite'] * $ravitaillement['prix']);
            $cumul_TVA_fournisseur = $cumul_TVA_fournisseur + (($ravitaillement['pourcentageTVA'] / 100) * ($ravitaillement['quantite'] * $ravitaillement['prix']));
        }
    }

    $cumul_total_all = $cumul_total_all + $cumul_total_fournisseur;
    $cumul_TVA_all = $cumul_TVA_all + $cumul_TVA_fournisseur;


    $r++;

    $objPHPExcel->setActiveSheetIndex(0)
            ->setCellValueByColumnAndRow(1, $r, "")
            ->setCellValueByColumnAndRow(2, $r, "Total : " . $cumul_total_fournisseur . " USD")
            ->setCellValueByColumnAndRow(3, $r, "Value TVA : " . $cumul_TVA_fournisseur . " USD")
            ->setCellValueByColumnAndRow(4, $r, "")
            ->setCellValueByColumnAndRow(5, $r, "")
            ->setCellValueByColumnAndRow(6, $r, "")
            ->setCellValueByColumnAndRow(7, $r, "")
            ->setCellValueByColumnAndRow(8, $r, "")
            ->setCellValueByColumnAndRow(9, $r, "");
}

$r++;
$r++;

$objPHPExcel->setActiveSheetIndex(0)
        ->setCellValueByColumnAndRow(1, $r, "")
        ->setCellValueByColumnAndRow(2, $r, 'Grand total Input value : ' . ($cumul_total_all . " USD"))
        ->setCellValueByColumnAndRow(3, $r, "")
        ->setCellValueByColumnAndRow(4, $r, "")
        ->setCellValueByColumnAndRow(5, $r, "")
        ->setCellValueByColumnAndRow(6, $r, "")
        ->setCellValueByColumnAndRow(7, $r, "")
        ->setCellValueByColumnAndRow(8, $r, "")
        ->setCellValueByColumnAndRow(9, $r, "");

$r++;
$r++;

$objPHPExcel->setActiveSheetIndex(0)
        ->setCellValueByColumnAndRow(1, $r, "")
        ->setCellValueByColumnAndRow(2, $r, 'TVA : ' . ($cumul_TVA_all . " USD"))
        ->setCellValueByColumnAndRow(3, $r, "")
        ->setCellValueByColumnAndRow(4, $r, "")
        ->setCellValueByColumnAndRow(5, $r, "")
        ->setCellValueByColumnAndRow(6, $r, "")
        ->setCellValueByColumnAndRow(7, $r, "")
        ->setCellValueByColumnAndRow(8, $r, "")
        ->setCellValueByColumnAndRow(9, $r, "");

$r++;
$r++;

$objPHPExcel->setActiveSheetIndex(0)
        ->setCellValueByColumnAndRow(1, $r, "")
        ->setCellValueByColumnAndRow(2, $r, 'Total + TVA : ' . (($cumul_total_all + $cumul_TVA_all) . " USD"))
        ->setCellValueByColumnAndRow(3, $r, "")
        ->setCellValueByColumnAndRow(4, $r, "")
        ->setCellValueByColumnAndRow(5, $r, "")
        ->setCellValueByColumnAndRow(6, $r, "")
        ->setCellValueByColumnAndRow(7, $r, "")
        ->setCellValueByColumnAndRow(8, $r, "")
        ->setCellValueByColumnAndRow(9, $r, "");


$objPHPExcel->getActiveSheet()->setTitle('Receipts report');


// Set active sheet index to the first sheet, so Excel opens this as the first sheet
$objPHPExcel->setActiveSheetIndex(0);

$objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');
ob_end_clean();
// We'll be outputting an excel file
header('Content-type: application/vnd.ms-excel');
header('Content-Disposition: attachment; filename="' . $titre_document . '".xlsx"');

$objWriter->save('php://output');
exit;
?>