<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
?>
<?php

require '../../../web/fpdf181/fpdf.php';

include("../../../models/pdf-generator/pdfclass.php");
include("../../../models/excel-generator/headerExcel.php");

require_once "../../../models/pdf-generator/PHPExcel-1.8/Classes/PHPExcel.php";
require_once '../../../models/pdf-generator/PHPExcel-1.8/Classes/PHPExcel/Writer/Excel2007.php';

include '../../../models/connexion.php';
include '../../../models/ravitaillement/ravitaillement.php';
include '../../../models/attribution-biens/attributionBiens.php';
include '../../../models/unite/unite.php';
include '../../../models/biens/biens.php';
include '../../../models/fournisseur/fournisseur.php';
?>

<?php

$objPHPExcel = new PHPExcel();


$objPHPExcel->setActiveSheetIndex(0)
        ->setCellValue('B4', getHeaderExcel());

$titre_document = "Receipts_report_" . date('Y-m-d');

$objPHPExcel->getProperties()->setCreator(getHeaderExcel())
        ->setLastModifiedBy(getHeaderExcel())
        ->setTitle($titre_document)
        ->setSubject("Store_inventory")
        ->setDescription("Inventory_report generated by UIGSoft")
        ->setKeywords(getHeaderExcel())
        ->setCategory(getHeaderExcel());

$label_document = "Purchase summary_report_";

$objPHPExcel->setActiveSheetIndex(0)
        ->setCellValue('B6', $label_document);

$n = 0;


$titre = "Purchase summary report ";

if ((isset($_GET['use_date1'])) && (isset($_GET['use_date2']))) {
    $titre = $titre . "Starting date : " . $_GET['use_date1'] . " " . " / Ending date : " . $_GET['use_date2'];
} else {
    $titre = $titre . " Choose interval";
}


if (isset($_GET['use_biens'])) {
    $bdbiens = new BdBiens();
    $biens = $bdbiens->getBiensById($_GET['use_biens']);
    foreach ($biens as $bien) {
        $designation_biens_choosen = $bien['bDesignation'] . " / " . $bien['gDesignation'];
    }
    if (isset($designation_biens_choosen)) {
        $titre = $titre . " Item :" . $designation_biens_choosen;
    } else {
        $titre = $titre . " | Item : - ";
    }
}

$r = 10;

$designation_fournisseur = "";
$bdfournisseur = new BdFournisseur();
$fournisseurs = $bdfournisseur->getFournisseurById($_GET['use_fournisseur']);
foreach ($fournisseurs as $fournisseur) {
    $designation_fournisseur = $fournisseur['designation'];
}

if ($designation_fournisseur == "") {
    $designation_fournisseur = "All";
}

$titre_document = $titre;

if ((isset($_GET['use_numeroOrder'])) && ($_GET['use_numeroOrder'] != "none")) {

    $r++;
    $r++;

    $objPHPExcel->setActiveSheetIndex(0)
            ->setCellValueByColumnAndRow(1, $r, "")
            ->setCellValueByColumnAndRow(2, $r, utf8_decode("Order number : " . $_GET['use_numeroOrder']))
            ->setCellValueByColumnAndRow(3, $r, "")
            ->setCellValueByColumnAndRow(4, $r, "")
            ->setCellValueByColumnAndRow(5, $r, "")
            ->setCellValueByColumnAndRow(6, $r, "")
            ->setCellValueByColumnAndRow(7, $r, "")
            ->setCellValueByColumnAndRow(8, $r, "")
            ->setCellValueByColumnAndRow(9, $r, "");
}

if ((isset($_GET['use_numeroOrder'])) && ($_GET['use_numeroOrder'] != "none")) {
    $bdattributionbiens = new BdAttributionBiens();
    $attributions = $bdattributionbiens->getAttributionBiensByNumeroOrder($_GET['use_numeroOrder']);
    foreach ($attributions as $attribution) {
        $id_fournisseur = $attribution['fId'];
    }
    $bdfournisseur = new BdFournisseur();
    $fournisseurs = $bdfournisseur->getFournisseurById($id_fournisseur);
    foreach ($fournisseurs as $fournisseur) {
        $designation_fournisseur = $fournisseur['designation'];
    }
}

$r++;
$r++;

$objPHPExcel->setActiveSheetIndex(0)
        ->setCellValueByColumnAndRow(1, $r, "")
        ->setCellValueByColumnAndRow(2, $r, utf8_decode($titre_document))
        ->setCellValueByColumnAndRow(3, $r, "")
        ->setCellValueByColumnAndRow(4, $r, "")
        ->setCellValueByColumnAndRow(5, $r, "")
        ->setCellValueByColumnAndRow(6, $r, "")
        ->setCellValueByColumnAndRow(7, $r, "")
        ->setCellValueByColumnAndRow(8, $r, "")
        ->setCellValueByColumnAndRow(9, $r, "");

$r++;
$r++;

$objPHPExcel->setActiveSheetIndex(0)
        ->setCellValueByColumnAndRow(1, $r, "")
        ->setCellValueByColumnAndRow(2, $r, decode('Supplier : ') . decode($designation_fournisseur))
        ->setCellValueByColumnAndRow(3, $r, "")
        ->setCellValueByColumnAndRow(4, $r, "")
        ->setCellValueByColumnAndRow(5, $r, "")
        ->setCellValueByColumnAndRow(6, $r, "")
        ->setCellValueByColumnAndRow(7, $r, "")
        ->setCellValueByColumnAndRow(8, $r, "")
        ->setCellValueByColumnAndRow(9, $r, "");

$r++;
$r++;

$objPHPExcel->setActiveSheetIndex(0)
        ->setCellValueByColumnAndRow(1, $r, "")
        ->setCellValueByColumnAndRow(2, $r, decode('Interval : ') . decode($_GET['use_date1'] . " to " . $_GET['use_date2']))
        ->setCellValueByColumnAndRow(3, $r, "")
        ->setCellValueByColumnAndRow(4, $r, "")
        ->setCellValueByColumnAndRow(5, $r, "")
        ->setCellValueByColumnAndRow(6, $r, "")
        ->setCellValueByColumnAndRow(7, $r, "")
        ->setCellValueByColumnAndRow(8, $r, "")
        ->setCellValueByColumnAndRow(9, $r, "");

$r++;
$r++;
$r++;


$objPHPExcel->setActiveSheetIndex(0)
        ->setCellValueByColumnAndRow(1, $r, "#")
        ->setCellValueByColumnAndRow(2, $r, "Supplier")
        ->setCellValueByColumnAndRow(3, $r, "Date")
        ->setCellValueByColumnAndRow(4, $r, "Value")
        ->setCellValueByColumnAndRow(5, $r, "TVA");

$n = 0;
$cumul_total_sortie = 0;
$cumul_total_reste = 0;
$cumul_total = 0;
$bdravitaillement = new BdRavitaillement();
if ((isset($_GET['use_biens'])) && ($_GET['use_biens'] != 0)) {
    if ((isset($_GET['use_date1'])) && ($_GET['use_date1'] != "")) {
        $ravitaillements = $bdravitaillement->getRavitaillementBetween2DatesByIdBiens($_GET['use_date1'], $_GET['use_date2'], $_GET['use_biens']);
    } else {
        $ravitaillements = $bdravitaillement->getRavitaillementByIdBiens($_GET['use_biens']);
    }
} else {
    if ((isset($_GET['use_date1'])) && ($_GET['use_date1'] != "")) {
        $ravitaillements = $bdravitaillement->getRavitaillementBetween2Dates($_GET['use_date1'], $_GET['use_date2']);
    } else {
        $ravitaillements = $bdravitaillement->getRavitaillementAllDesc();
    }
}

if ((isset($_GET['use_numeroOrder'])) && ($_GET['use_numeroOrder'] != "none")) {
    $ravitaillements = $bdravitaillement->getRavitaillementByNumeroOrder($_GET['use_numeroOrder']);
}

$bdfournisseur = new BdFournisseur();
if ((isset($_GET['use_fournisseur'])) && ($_GET['use_fournisseur'] != 0)) {
    $fournisseurs = $bdfournisseur->getFournisseurById($_GET['use_fournisseur']);
} else {
    $fournisseurs = $bdfournisseur->getFournisseurAllDesc();
}

if ((isset($_GET['use_numeroOrder'])) && ($_GET['use_numeroOrder'] != "none")) {
    $bdattributionbiens = new BdAttributionBiens();
    $attributions = $bdattributionbiens->getAttributionBiensByNumeroOrder($_GET['use_numeroOrder']);
    foreach ($attributions as $attribution) {
        $id_fournisseur = $attribution['fId'];
    }
    $bdfournisseur = new BdFournisseur();
    $fournisseurs = $bdfournisseur->getFournisseurById($id_fournisseur);
}

$cumul_total_all = 0;
$cumul_TVA_all = 0;
foreach ($fournisseurs as $fournisseur) {
    $cumul_total_fournisseur = 0;
    $cumul_TVA_fournisseur = 0;


    $r++;
    $r++;

    $objPHPExcel->setActiveSheetIndex(0)
            ->setCellValueByColumnAndRow(1, $r, "")
            ->setCellValueByColumnAndRow(2, $r, $fournisseur['designation'])
            ->setCellValueByColumnAndRow(3, $r, "")
            ->setCellValueByColumnAndRow(4, $r, "")
            ->setCellValueByColumnAndRow(5, $r, "");

    $date_array = [];
    foreach ($ravitaillements as $ravitaillement) {
        if (!in_array($ravitaillement['date'], $date_array)) {
            array_push($date_array, $ravitaillement['date']);
        }
    }

    foreach ($date_array as $date_item) {

        $cumul_value_date = 0;
        $cumul_TVA_date = 0;
        $n++;
        foreach ($ravitaillements as $ravitaillement) {

            if (($ravitaillement['date'] == $date_item)) {
                if ($ravitaillement['fournisseur_id'] == $fournisseur['id']) {

                    $cumul_value_date = $cumul_value_date + ($ravitaillement['quantite'] * $ravitaillement['prix']);

                    $cumul_TVA_date = $cumul_TVA_date + (($ravitaillement['pourcentageTVA'] / 100) * ($ravitaillement['quantite'] * $ravitaillement['prix']));
                }
            }
        }
        $cumul_total_fournisseur = $cumul_total_fournisseur + ($cumul_value_date);
        $cumul_TVA_fournisseur = $cumul_TVA_fournisseur + ($cumul_TVA_date);
        if ($cumul_value_date != 0) {
            $r++;

            $objPHPExcel->setActiveSheetIndex(0)
                    ->setCellValueByColumnAndRow(1, $r, "")
                    ->setCellValueByColumnAndRow(2, $r, "")
                    ->setCellValueByColumnAndRow(3, $r, $date_item)
                    ->setCellValueByColumnAndRow(4, $r, $cumul_value_date)
                    ->setCellValueByColumnAndRow(5, $r, $cumul_TVA_date);
        }
    }

   

    $cumul_total_all = $cumul_total_all + $cumul_total_fournisseur;
    $cumul_TVA_all = $cumul_TVA_all + $cumul_TVA_fournisseur;


    $r++;

    $objPHPExcel->setActiveSheetIndex(0)
            ->setCellValueByColumnAndRow(1, $r, "")
            ->setCellValueByColumnAndRow(2, $r, "Total : " . $cumul_total_fournisseur . " USD")
            ->setCellValueByColumnAndRow(3, $r, "Value TVA : " . $cumul_TVA_fournisseur . " USD")
            ->setCellValueByColumnAndRow(4, $r, "")
            ->setCellValueByColumnAndRow(5, $r, "");
}

$r++;
$r++;

$objPHPExcel->setActiveSheetIndex(0)
        ->setCellValueByColumnAndRow(1, $r, "")
        ->setCellValueByColumnAndRow(2, $r, 'Grand total Input value : ' . ($cumul_total_all . " USD"))
        ->setCellValueByColumnAndRow(3, $r, "")
        ->setCellValueByColumnAndRow(4, $r, "")
        ->setCellValueByColumnAndRow(5, $r, "");

$r++;
$r++;

$objPHPExcel->setActiveSheetIndex(0)
        ->setCellValueByColumnAndRow(1, $r, "")
        ->setCellValueByColumnAndRow(2, $r, 'TVA : ' . ($cumul_TVA_all . " USD"))
        ->setCellValueByColumnAndRow(3, $r, "")
        ->setCellValueByColumnAndRow(4, $r, "")
        ->setCellValueByColumnAndRow(5, $r, "");

$r++;
$r++;

$objPHPExcel->setActiveSheetIndex(0)
        ->setCellValueByColumnAndRow(1, $r, "")
        ->setCellValueByColumnAndRow(2, $r, 'Total + TVA : ' . (($cumul_total_all + $cumul_TVA_all) . " USD"))
        ->setCellValueByColumnAndRow(3, $r, "")
        ->setCellValueByColumnAndRow(4, $r, "")
        ->setCellValueByColumnAndRow(5, $r, "");


$objPHPExcel->getActiveSheet()->setTitle("Purchase Summary Report");


// Set active sheet index to the first sheet, so Excel opens this as the first sheet
$objPHPExcel->setActiveSheetIndex(0);

$objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');
ob_end_clean();
// We'll be outputting an excel file
header('Content-type: application/vnd.ms-excel');
header('Content-Disposition: attachment; filename="' . $titre_document . '".xlsx"');

$objWriter->save('php://output');
exit;
?>